---

- name: Manage Apache
  hosts: all
  become: true
  become_user: root
  tasks:
          - name: Update and upgrade cache
            ansible.builtin.apt:
                    update_cache: yes
                    upgrade: yes
          
          
          
          - name: Install Apache
            ansible.builtin.apt:
                    name: apache2
                    state: latest
          
          - name: Install PHP
            ansible.builtin.apt:
                    name: libapache2-mod-php
                    state: latest
